name: Deploy and Scan Static Site

on:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java (required by SonarScanner)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: "17"

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=lokeshsolanki12
            -Dsonar.projectKey=lokeshsolanki12_SECURE_DEVOPS-_PRACTICES
            -Dsonar.cloud.enabled=false

  deploy:
    needs: build-and-scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.TOKENTASK }}
          publish_dir: .
